### ISSUE TITLE
execute_script works locally but not on ci

### ISSUE THREAD

**Issue by Eraldo** [hitchtest/hitchtest#6]
Hey..

I wrote this step:

``` python
    def scroll_to(self, id):
        """Scroll to an element."""
        self.driver.execute_script('$("#{}").get(0).scrollIntoView();'.format(id))
```

It works locally. It does not work on travis.
I have no idea why.

(This might not have anything to do with hitchtest.. but I am not sure about that.)

The step is executed on ci without getting an error.. but further down the line.. I found out that it in fact was suck at that exact stage.

Any ideas?

**Comment by crdoconnor** [comment]
Is this something to do with XVFB perhaps? If you run it with XVFB set to true on your local machine does it do the same thing?

**Comment by Eraldo** [comment]
I'll try that and report back. :)

**Comment by Eraldo** [comment]
I get:
"Hitch can't use xvfb on Mac OS X"

Is there anything else to find the source of the problem apart from creating a local setup for headless testing?

The strange thing is that I have these steps:

``` yaml
    # Carolina looked at the landing page and now wants to join coLegend.
    # She opens the site, scrolls down and clicks on the join button:
    - Load website
    - Scroll to: join-explorer
    - Click: join-explorer

    # She comes to a chat page were she is greeted and asked how she wants to join:
    - Page title: Join
    - Find text: Welcome
    - Find text: How do you want to join?
```

I do not get any error for `Scroll to: join-explorer` or `Click: join-explorer` .. as if it worked.. and then for `Page title: Join` I get an error telling me that the page is still "About" (the stating page).
That is so strange!

Why can that be?

**Comment by crdoconnor** [comment]
Oops sorry @Eraldo this dropped off my radar.

This looks a bit like your scroll to code is triggering the javascript but the javascript hasn't fully finished executing before the click is executed. So the click ends up doing nothing.

This is a fairly common selenium problem that occurs when you start running things headless because everything runs much quicker in headless mode. It's basically a race condition.

It's commonly solved by adding a short sleep which would certainly work here, but that's a bad way to approach the problem. (See https://hitchtest.readthedocs.org/en/latest/glossary/sleep_oriented_testing.html).

If you make the join-explorer button invisible or disabled until _after_ the javascript is done attaching its event handler (or whatever it is it is your JS is doing) and have a "wait-to-appear: join-explorer" step it should solve the problem.

**Comment by Eraldo** [comment]
I have tried adding a 4 second wait (sleep call) and a wait-to-appear ..which both still did what it should locally.

On travis:
No error from the wait-to-appear.. and neither one from the click.
However .. travis still was stuck at the 'About' page!
I do not get why yet.

My join-explorer template code looks like this:

``` html
<div class="col-lg-4 wow zoomIn">
  ...
  <a id="join-explorer" class="btn btn-info btn-lg" href="{% url "join" %}?next=/">Join</a>
</div>
```

The `wow zoomIn` classes are what create the animation.
(https://github.com/matthieua/WOW)

I will do a sanity check now by removing these classes and seeing that gets the build to pass. :)
Will report back as soon as it is done.

**Comment by crdoconnor** [comment]
Odder and odder.

Do you have a linux machine you can run the test on? (a virtual machine should do).

I'm starting to wonder now if it might not be that the javascript / the rest of your static files are not loading on travis.

Do you need to run collectstatic to get it to run on your macbook?

**Comment by Eraldo** [comment]
Good idea.. I am downloading Virtualbox now and will try to set it up and run int under Ubuntu.

Just did some further tests.
Added a "Wait to appear: join-explorer" right after scrolled join click.

``` yaml
    # She opens the site, scrolls down and clicks on the join button:
    - Load website
    - Wait: 4
    - Find text: "Pricing"
    - Scroll to: join-explorer
    - Click: join-explorer

    # She comes to a chat page were she is greeted and asked how she wants to join:
    - Wait to appear: regular-signup
```

That got me a Timeout exception: `selenium.common.exceptions.TimeoutException`
So it is a javascript issue.
And the javascript must load, or else the class would do nothing and the click would be a normal click.
Odd, yes.
